### ISSUE TITLE
Drivers Standing up to a given race

### ISSUE THREAD

**Issue by brombomb** [brombomb/f1hub#2]
Be able to see the drivers standing up to a given race in the season.  This will prevent spoilers while watching a race.

**Comment by arianahl** [comment]
Hi @brombomb, I can take this one. 
I imagine you expect a list of races on the driver standings landing page and once one is selected you would see the standings list? 
Or do you want to be able to access the standing for the race in the Hub? (similar to the results)

**Comment by brombomb** [comment]
I imagine from the hub being able to click through to see the drivers standings up to that point.

**Comment by arianahl** [comment]
I'm struggling to start the app. When doing `npm install` I get the following:
`$ npm install

> gifsicle@0.1.7 postinstall /Users/arianahl/opensource/f1hub/node_modules/gifsicle
> node index.js

path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received { url: 'https://raw.github.com/imagemin/gifsicle-bin/v0.1.7/vendor/osx/gifsicle',
  name: 'gifsicle',
  os: 'darwin' }
    at assertPath (path.js:7:11)
    at Object.basename (path.js:1355:5)
    at /Users/arianahl/opensource/f1hub/node_modules/download/index.js:35:43
    at each (/Users/arianahl/opensource/f1hub/node_modules/each-async/each-async.js:63:4)
    at module.exports (/Users/arianahl/opensource/f1hub/node_modules/download/index.js:33:5)
    at /Users/arianahl/opensource/f1hub/node_modules/bin-wrapper/index.js:108:20
    at /Users/arianahl/opensource/f1hub/node_modules/bin-wrapper/index.js:141:24
    at /Users/arianahl/opensource/f1hub/node_modules/bin-check/index.js:30:20
    at /Users/arianahl/opensource/f1hub/node_modules/executable/index.js:39:20
    at FSReqWrap.oncomplete (fs.js:123:15)
`

**Comment by arianahl** [comment]
There is obviously something wrong with version 0.3.0 of grunt-contrib-imagemin. Once I bump it to v2.0.1 it all works.
