### ISSUE TITLE
Fix automerge gh-pages action

### ISSUE THREAD

**Issue by brombomb** [brombomb/f1hub#32]
We want to merge master into `gh-pages` so it's deployed automatically.

**Comment by pururaj987** [comment]
So , the last command i.e. "git merge main" is not running?

**Comment by pururaj987** [comment]
I guess it's a syntax error when writing gh-pages , I will look at it again.

**Comment by pururaj987** [comment]
I changed the yaml code , could you please review PR #37

**Comment by pururaj987** [comment]
@brombomb I went through it , could you please check PR #38
