### ISSUE TITLE
Wrong number representation

### ISSUE THREAD

**Issue by ayush-wd** [brombomb/f1hub#46]
The driver's number should not have a space between the space and the actual number.
Ex. it should be '#33' not '# 33'
Also Max Verstappen's number is '#1' however it is shown as '33' on the website

**Comment by ayush-wd** [comment]
I'm getting issues while trying to commit sir and now I am getting a message that I cannot comment on the previous issue right now.

**Comment by brombomb** [comment]
The results are pulled from `permanent number` which is Max's number.  You can change it to use the parent object `number` to get `#1` for Max instead of `#33`.

**Comment by brombomb** [comment]
> I'm getting issues while trying to commit sir and now I am getting a message that I cannot comment on the previous issue right now.

I think I fixed the merging issue again.  merge master into your branch, and make sure you have no merge conflicts

**Comment by ayush-wd** [comment]
Thank you sir, I think it's working now. You can accept the pull request now.

**Comment by ayush-wd** [comment]
The parent object number is present in which file?
