### ISSUE TITLE
Feature: Add a favico

### ISSUE THREAD

**Issue by brombomb** [brombomb/f1hub#78]
Something like this

https://www.flaticon.com/free-icon/racing-car_1506369

Preferably in Mercedes colors red bull colors will not be accepted

**Comment by sarafurd** [comment]
please assign this to me

**Comment by algoplutus1708** [comment]
Please assign this issue to me , I plan to create a pull request during the month of October so that it can be counted towards Hacktoberfest 2023. Thank u!!
