### ISSUE TITLE
Feature:  Replace ergast with jolpica

### ISSUE THREAD

**Issue by brombomb** [brombomb/f1hub#89]
Data API is being deprecated at the end of the 2024 season. Move to the new API which should be a drop in replacement.

https://github.com/jolpica/jolpica-f1

**Comment by Kannav02** [comment]
Hey @brombomb !

I've explored the codebase and I just wanted to clarify some points regarding the same

1) The controllers in the main.js file should support the new API and proper parsing of content should be made available to the respective views in the views folder
2) Look for any discrepancies with how the new API is handling the data, although I think this wouldn't be difficult as the new API has backward compatibility 

if these are all the changes, I would love to work on this issue, thank you!

**Comment by brombomb** [comment]
Yup. It really should be as simple as a base URL swap. Just make a PR and
reference this issue.

**Comment by Kannav02** [comment]
sure! 
I will start working on this

thank you!

**Comment by Kannav02** [comment]
@brombomb just to clarify something before I make a change, angular isn't allowing me to make requests to the API due to CORS issues, is it okay if I use a proxy configuration to forward the request to the API?

**Comment by brombomb** [comment]
Can you make a PR marked as draft with he apo changes?  Seems weird and I'm wondering if there's something else missing.  I'd rather not add a proxy

**Comment by Kannav02** [comment]
sure, I would do so
just a quick update though, I went through the APIs repository, and an issue regarding CORS was raised 2 weeks ago, apparently, its fixed over there but I do get the CORS error when I make a request from angular,

**Comment by Kannav02** [comment]
update, I found the fix

I went through another repo that was utilizing this API and found the fix, I'll get this working soon

**Comment by brombomb** [comment]
Awesome, thanks for the update!

**Comment by Kannav02** [comment]
Hey @brombomb 

PR #91 should address and fix this issue

Thank you!

**Comment by brombomb** [comment]
Thanks for the PR and your patience!
