### ISSUE TITLE
Sort by Qualifying Times (Q1/Q2)

### ISSUE THREAD

**Issue by brombomb** [brombomb/f1hub#9]
Allow sorting of the quali times by the column headers Q1 and Q2. Keep the default sort order.  Allow to sort by quali order

**Comment by tchesa** [comment]
@brombomb i'd like to work on this

**Comment by brombomb** [comment]
Should be pretty easy. Copy the other columns and make a PR.

**Comment by tchesa** [comment]
Yeah it should. Assign it to me please, i work on this later today
